#! /bin/bash

set -euo pipefail

sqlite3 geograph.sqlite3 <<EOF
  CREATE TABLE gridimage_base (
    gridimage_id INTEGER PRIMARY KEY,
    user_id INTEGER,
    realname TEXT,
    title TEXT,
    moderation_status TEXT,
    imagetaken TEXT,
    grid_reference TEXT,
    x INTEGER, y INTEGER,
    wgs84_lat REAL, wgs84_long REAL,
    reference_index INTEGER
    );
EOF
if [ -f gridimage_base.mysql.gz ]; then
    {
	echo "BEGIN;"
	gzip -dc gridimage_base.mysql.gz | { grep -a '^INSERT' || true; } | sed "s/\\\\'/''/g"
	echo "UPDATE gridimage_base SET title = NULL;"
	echo "COMMIT;"
    } | sqlite3 geograph.sqlite3
elif [ -f  gridimage_base.tsv.gz ]; then
    gzip -dc gridimage_base.tsv.gz | sed '1d;s/"/\\"/g' |
	sqlite3 geograph.sqlite3 ".mode tabs" ".import /dev/stdin gridimage_base"
fi

sqlite3 geograph.sqlite3 <<EOF
  CREATE TABLE gridimage_geo (
    gridimage_id INTEGER PRIMARY KEY,
    nateastings INTEGER, natnorthings INTEGER, natgrlen TEXT,
    viewpoint_eastings INTEGER, viewpoint_northings TEXT,
    viewpoint_grlen INTEGER,
    view_direction INTEGER,
    use6fig INTEGER
    );
EOF
if [ -f gridimage_geo.mysql.gz ]; then
    {
	echo "BEGIN;"
	gzip -dc gridimage_geo.mysql.gz  | { grep -a '^INSERT' || true; } | sed "s/\\\\'/''/g"
	echo "COMMIT;"
    } | sqlite3 geograph.sqlite3
elif [ -f  gridimage_geo.tsv.gz ]; then
    gzip -dc gridimage_geo.tsv.gz | sed '1d;s/"/\\"/g' |
	sqlite3 geograph.sqlite3 ".mode tabs" ".import /dev/stdin gridimage_geo"
fi

sqlite3 geograph.sqlite3 <<EOF
  CREATE TABLE gridimage_size (
    gridimage_id INTEGER PRIMARY KEY,
    width INTEGER,
    height INTEGER,
    original_width INTEGER,
    original_height INTEGER,
    original_diff TEXT
    );
EOF

if [ -f gridimage_size.mysql.gz ]; then
    {
	echo "BEGIN;"
	gzip -dc gridimage_size.mysql.gz | { grep -a '^INSERT' || true; } | sed "s/\\\\'/''/g"
	echo "COMMIT;"
    } | sqlite3 geograph.sqlite3
elif [ -f  gridimage_size.tsv.gz ]; then
    gzip -dc gridimage_size.tsv.gz | sed '1d;s/"/\\"/g' |
	sqlite3 geograph.sqlite3 ".mode tabs" ".import /dev/stdin gridimage_size"
fi
