#! /bin/bash

set -euo pipefail

function fetch {
    wget ${WGET_OPTIONS-} "${@}"
}

fetch 'http://data.geograph.org.uk/dumps/gridimage_base.tsv.gz' \
      'http://data.geograph.org.uk/dumps/gridimage_extra.tsv.gz' \
      'http://data.geograph.org.uk/dumps/gridimage_geo.tsv.gz' \
      'http://data.geograph.org.uk/dumps/gridimage_size.tsv.gz'
