#! /usr/bin/python3

from __future__ import division, print_function, unicode_literals
import sqlite3
from location import location_from_row, object_location_from_row
import sys
from gubutil import connect_geograph_db

geodb = connect_geograph_db()
geodb.row_factory = sqlite3.Row

def main():
        gridimage_id = int(sys.argv[1])
        c = geodb.cursor()
        c.execute("""
            SELECT * FROM gridimage_base NATURAL JOIN gridimage_geo
               WHERE gridimage_id = ?
            """, (gridimage_id,))
        row = c.fetchone()
        if row == None:
            raise NotInGeographDatabase("Geograph ID %d not in database" %
                                        (gridimage_id,))
        l = location_from_row(row)
        if l: print(l)
        ol = object_location_from_row(row)
        if ol: print(ol)
        
main()
